name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Cache dependencies
      uses: actions/cache@master
      with:
        path: Carthage
        key: ${{ runner.os }}-build-${{ hashFiles('Cartfile.resolved') }}
    - name: Update Dependencies
      run: carthage update --cache-builds --platform iOS 
    - name: Build the App
      run: |
        cp Source/info.plist Source/Biu.plist
        xcodebuild clean build CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO
        
